import next from "eslint-config-next/core-web-vitals";

/**
 * Flat config, replacing .eslintrc.json.
 *
 * eslint-config-next 16 exports a real flat-config ARRAY (next, next/typescript,
 * next/core-web-vitals, plus its own ignores), so it spreads in directly and no
 * FlatCompat shim is needed.
 *
 * Scope note that matters: the old command was `eslint . --ext .ts,.tsx`, and
 * `--ext` does not exist in flat config. File selection now comes from the
 * `files` patterns inside each config object instead of from the CLI, so the
 * lint script is just `eslint .`. Do not try to reintroduce `--ext`; it is a
 * hard error, not a deprecation warning.
 */
const config = [
  ...next,

  {
    /* Build output, dependencies and generated artifacts. Kept explicit rather
       than inherited, so what is NOT linted is reviewable in one place. */
    ignores: [
      ".next/**",
      "node_modules/**",
      "next-env.d.ts",
      /* GENERATED by scripts/generate-signature.cjs and verified byte for byte by
         verify:signature. Linting it would invite a formatting autofix that breaks
         reproducibility, which is a real failure mode here, not a hypothetical. */
      "src/constants/signature.ts",
    ],
  },
];

export default config;
